# Generated by Django 6.0.3 on 2026-03-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('book_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Номер сервисной книжки')),
                ('moped_model', models.CharField(max_length=100, verbose_name='Модель мопеда')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Имя владельца')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Гос. номер')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='OilChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата замены')),
                ('oil_type', models.CharField(max_length=100, verbose_name='Тип масла')),
                ('oil_volume', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объём масла (л)')),
                ('filter_replaced', models.BooleanField(default=False, verbose_name='Фильтр заменён')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег (км)')),
                ('oil_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость масла (₸)')),
                ('filter_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Себестоимость фильтра (₸)')),
                ('price_charged', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена для клиента (₸)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_changes', to='service.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Замена масла',
                'verbose_name_plural': 'Замены масла',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OilSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата продажи')),
                ('oil_type', models.CharField(max_length=100, verbose_name='Тип масла')),
                ('oil_volume', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объём (л)')),
                ('oil_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость (₸)')),
                ('price_charged', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи (₸)')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_sales', to='service.client', verbose_name='Клиент (если есть)')),
            ],
            options={
                'verbose_name': 'Продажа масла',
                'verbose_name_plural': 'Продажи масла',
                'ordering': ['-date'],
            },
        ),
    ]
