# Generated by Django 6.0.3 on 2026-03-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название масла')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость за 1л (₸)')),
            ],
        ),
        migrations.RemoveField(
            model_name='oilchange',
            name='oil_type',
        ),
        migrations.RemoveField(
            model_name='oilsale',
            name='oil_type',
        ),
        migrations.AlterField(
            model_name='oilchange',
            name='oil_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Себестоимость масла (₸)'),
        ),
        migrations.AlterField(
            model_name='oilsale',
            name='oil_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Себестоимость (₸)'),
        ),
        migrations.AddField(
            model_name='oilchange',
            name='oil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.oil', verbose_name='Масло'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oilsale',
            name='oil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.oil', verbose_name='Масло'),
            preserve_default=False,
        ),
    ]
